version: '3.8'

services:
  # Spring Boot API
  tara-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tara-api
    restart: unless-stopped
    ports:
      - "9999:9999"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms512m -Xmx1024m
      # Database config (nếu muốn override)
      # - SPRING_DATASOURCE_URL=jdbc:postgresql://212.85.25.175:5432/taradb
      # - SPRING_DATASOURCE_USERNAME=postgres
      # - SPRING_DATASOURCE_PASSWORD=slm123slm123
    networks:
      - tara-network
#    healthcheck:
#      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9999/actuator/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: tara-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
      # SSL certificates (nếu có)
      # - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      tara-api:
        condition: service_healthy
    networks:
      - tara-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  tara-network:
    driver: bridge
    name: tara-network

# Volumes (nếu cần persist data)
# volumes:
#   postgres-data:
#   redis-data: