version: '3.8'

services:
  # Spring Boot API
  slm-api-v2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slm-api-v2
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms512m -Xmx1024m
      # Database config (nếu muốn override)
      # - SPRING_DATASOURCE_URL=jdbc:postgresql://212.85.25.175:5432/taradb
      # - SPRING_DATASOURCE_USERNAME=postgres
      # - SPRING_DATASOURCE_PASSWORD=slm123slm123
    networks:
      - slm-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: slm-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
      # SSL certificates (nếu có)
      # - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      slm-api-v2:
        condition: service_healthy
    networks:
      - slm-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  slm-network:
    driver: bridge
    name: slm-network

# Volumes (nếu cần persist data)
# volumes:
#   postgres-data:
#   redis-data: